#ifndef FACEDETECTORDLL_GLOBAL_H
#define FACEDETECTORDLL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(FACEDETECTORDLL_LIBRARY)
#  define FACEDETECTORDLLSHARED_EXPORT Q_DECL_EXPORT
#else
#  define FACEDETECTORDLLSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // FACEDETECTORDLL_GLOBAL_H
